<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Entry_khs_model extends CI_Model
{
    var $table_q='qnilai';
    var $table_nilai='nilai';

    public $table = 'entry_khs';
    public $id = 'identry_khs';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('identry_khs', $q);
	$this->db->or_like('table_mahasiswa_nim', $q);
	$this->db->or_like('table_matakuliah_kode_matakuliah', $q);
	$this->db->or_like('table_nilai_id_nilai', $q);
	$this->db->or_like('table_semester_id_semester', $q);
	$this->db->or_like('tahun_ajaran', $q);
	$this->db->or_like('sksn', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('identry_khs', $q);
	$this->db->or_like('table_mahasiswa_nim', $q);
	$this->db->or_like('table_matakuliah_kode_matakuliah', $q);
	$this->db->or_like('table_nilai_id_nilai', $q);
	$this->db->or_like('table_semester_id_semester', $q);
	$this->db->or_like('tahun_ajaran', $q);
	$this->db->or_like('sksn', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

    public function ambil_provinsi() {
    $sql_prov=$this->db->get($this->table_q);    
    if($sql_prov->num_rows()>0){
        foreach ($sql_prov->result_array() as $row)
            {
                $result['-']= '- Pilih nim -';
                $result[$row['nim']]= ucwords(strtolower($row['nim']));
            }
            return $result;
        }
    }


     public function get_semester()
        {
            $this->db->order_by('nama_semester', 'asc');
            return $this->db->get('table_semester')->result();
        }

     public function get_tahun_ajaran()
        {
            $this->db->order_by('tahun_ajaran', 'asc');
            return $this->db->get('table_ta')->result();
        }

    public function ambil_kabupaten($nim){
    $this->db->where('nim',$nim);
    $this->db->order_by('kode_matakuliah','asc');
    $sql_kabupaten=$this->db->get($this->table_q);
    if($sql_kabupaten->num_rows()>0){

        foreach ($sql_kabupaten->result_array() as $row)
        {
            $result[$row['kode_matakuliah']]= ucwords(strtolower($row['nama_matakuliah']));
        }
        } else {
           $result['-']= 'Data dengan nim tersebut kosong !!!';
        }
        return $result;
    }

    public function ambil_kecamatan($kode_kab){
    $this->db->where('kode_matakuliah',$kode_kab);
    $this->db->order_by('grade','asc');
    $sql_kecamatan=$this->db->get($this->table_q);
    if($sql_kecamatan->num_rows()>0){

        foreach ($sql_kecamatan->result_array() as $row)
        {
            $result[$row['id_nilai']]= ucwords(strtolower($row['grade']));
        }
        } else {
           $result['-']= '- Nilai masih kosong -';
        }
        return $result;
    }

}

/* End of file Entry_khs_model.php */
/* Location: ./application/models/Entry_khs_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-01-06 01:51:36 */
/* http://harviacode.com */