<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Model_kurikulum extends CI_Model
{

    public $table = 'kurikulum';
    public $id = 'id_kurikulum';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->escape_like_str('id_kurikulum', $q)."%' ESCAPE '!'";
	$this->db->escape_like_str('tahun', $q)."%' ESCAPE '!'";
	$this->db->escape_like_str('ket', $q)."%' ESCAPE '!'";
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->escape_like_str('id_kurikulum', $q)."%' ESCAPE '!'";
	$this->db->escape_like_str('tahun', $q)."%' ESCAPE '!'";
	$this->db->escape_like_str('ket', $q)."%' ESCAPE '!'";
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Model_kurikulum.php */
/* Location: ./application/models/Model_kurikulum.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-12-15 06:37:49 */
/* http://harviacode.com */