<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Modelmahasiswa extends CI_Model
{

    public $table = 'mahasiswa';
    public $id = 'nim';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    function id($nim)
    {
        $this->db->where($this->id, $nim);
        return $this->db->get($this->table)->row();
    }

    function cek_nim($nim){
         
        $sql = "select * from table_mahasiswa where nim='$nim'";
         
        $hasil = $this->db->query($sql);
         
        return $hasil->result();
         
    }

    function get_by_angkatan($q)
    {
        $this->db->where($this->angkatan, $q);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
	$this->db->like('nim', $q);
	$this->db->or_like('nama_mahasiswa', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('angkatan', $q);
	$this->db->or_like('sekolah_asal', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('gol_darah', $q);
	$this->db->or_like('photo', $q);
	$this->db->from($this->table);
       return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
    $this->db->order_by($this->id, $this->order);
	$this->db->like('nim', $q);
	$this->db->or_like('nama_mahasiswa', $q);
	$this->db->or_like('tgl_lahir', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('jenis_kelamin', $q);
	$this->db->or_like('alamat', $q);
	$this->db->or_like('angkatan', $q);
	$this->db->or_like('sekolah_asal', $q);
	$this->db->or_like('no_hp', $q);
	$this->db->or_like('gol_darah', $q);
	$this->db->or_like('photo', $q);
	$this->db->limit($limit, $start);
    return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Modelmahasiswa.php */
/* Location: ./application/models/Modelmahasiswa.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-28 14:43:54 */
/* http://harviacode.com */