<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Proses_khs extends CI_Model
{

    public $table = 'entry_khs';
    public $id = 'identry_khs';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function nim()
    {
        $q = $this->db->query("select * from qnilai");
        return $q;
    }
    function get_matakuliah($id)
    {
        $q = $this->db->query("select kode_matakuliah from qnilai where nim='$id'");
        return $q;
    }

}

/* End of file Entry_khs_model.php */
/* Location: ./application/models/Entry_khs_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-01-06 01:51:36 */
/* http://harviacode.com */