<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Qkhs_model extends CI_Model
{

    public $table = 'qkhs';
    public $id = '';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
	$this->db->or_like('identry_khs', $q);
	$this->db->or_like('nim', $q);
	$this->db->or_like('nama_mahasiswa', $q);
	$this->db->or_like('kode_matakuliah', $q);
	$this->db->or_like('nama_matakuliah', $q);
	$this->db->or_like('sks', $q);
	$this->db->or_like('nilai', $q);
	$this->db->or_like('grade', $q);
	$this->db->or_like('sksn', $q);
	$this->db->or_like('nama_semester', $q);
	$this->db->or_like('tahun_ajaran', $q);
	$this->db->from($this->table);
         return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
	$this->db->or_like('identry_khs', $q);
	$this->db->or_like('nim', $q);
	$this->db->or_like('nama_mahasiswa', $q);
	$this->db->or_like('kode_matakuliah', $q);
	$this->db->or_like('nama_matakuliah', $q);
	$this->db->or_like('sks', $q);
	$this->db->or_like('nilai', $q);
	$this->db->or_like('grade', $q);
	$this->db->or_like('sksn', $q);
	$this->db->or_like('nama_semester', $q);
	$this->db->or_like('tahun_ajaran', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Qkhs_model.php */
/* Location: ./application/models/Qkhs_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-01-17 10:13:22 */
/* http://harviacode.com */