<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Table_nilai_stase_besar_model extends CI_Model
{

    public $table = 'nilai_stase_besar';
    public $id = 'idtable_nilai_stase';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idtable_nilai_stase', $q);
	$this->db->or_like('table_stase_idtable_stase', $q);
    $this->db->or_like('table_koas_nim', $q);
	$this->db->or_like('mini_cex', $q);
	$this->db->or_like('mini_cex2', $q);
	$this->db->or_like('cbd', $q);
	$this->db->or_like('cbd2', $q);
	$this->db->or_like('dops', $q);
	$this->db->or_like('dops2', $q);
	$this->db->or_like('pylhn', $q);
	$this->db->or_like('pylhn2', $q);
	$this->db->or_like('j_reading', $q);
	$this->db->or_like('j_reading2', $q);
	$this->db->or_like('nform', $q);
	$this->db->or_like('ujian_lisan', $q);
	$this->db->or_like('n_lisan', $q);
	$this->db->or_like('ujian_tulis', $q);
	$this->db->or_like('n_tulis', $q);
	$this->db->or_like('kondite', $q);
	$this->db->or_like('nilai_angka', $q);
	$this->db->or_like('nilai_huruf', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idtable_nilai_stase', $q);
	$this->db->or_like('table_stase_idtable_stase', $q);
    $this->db->or_like('table_koas_nim', $q);
	$this->db->or_like('mini_cex', $q);
	$this->db->or_like('mini_cex2', $q);
	$this->db->or_like('cbd', $q);
	$this->db->or_like('cbd2', $q);
	$this->db->or_like('dops', $q);
	$this->db->or_like('dops2', $q);
	$this->db->or_like('pylhn', $q);
	$this->db->or_like('pylhn2', $q);
	$this->db->or_like('j_reading', $q);
	$this->db->or_like('j_reading2', $q);
	$this->db->or_like('nform', $q);
	$this->db->or_like('ujian_lisan', $q);
	$this->db->or_like('n_lisan', $q);
	$this->db->or_like('ujian_tulis', $q);
	$this->db->or_like('n_tulis', $q);
	$this->db->or_like('kondite', $q);
	$this->db->or_like('nilai_angka', $q);
	$this->db->or_like('nilai_huruf', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Table_nilai_stase_besar_model.php */
/* Location: ./application/models/Table_nilai_stase_besar_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-27 23:34:56 */
/* http://harviacode.com */