<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Table_ukmppd_model extends CI_Model
{

    public $table = 'ukmppd';
    public $id = 'idtable_ukmppd';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('idtable_ukmppd', $q);
	$this->db->or_like('table_koas_nim', $q);
	$this->db->or_like('yudisium', $q);
	$this->db->or_like('buku', $q);
	$this->db->or_like('administrasi', $q);
	$this->db->or_like('ktp', $q);
	$this->db->or_like('akta_kelahiran', $q);
	$this->db->or_like('ktm', $q);
	$this->db->or_like('ijasah_sked', $q);
	$this->db->or_like('ijasah_sma', $q);
	$this->db->or_like('photo', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('idtable_ukmppd', $q);
	$this->db->or_like('table_koas_nim', $q);
	$this->db->or_like('yudisium', $q);
	$this->db->or_like('buku', $q);
	$this->db->or_like('administrasi', $q);
	$this->db->or_like('ktp', $q);
	$this->db->or_like('akta_kelahiran', $q);
	$this->db->or_like('ktm', $q);
	$this->db->or_like('ijasah_sked', $q);
	$this->db->or_like('ijasah_sma', $q);
	$this->db->or_like('photo', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Table_ukmppd_model.php */
/* Location: ./application/models/Table_ukmppd_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-02-27 02:22:08 */
/* http://harviacode.com */